### ISSUE TITLE
test

### ISSUE THREAD

**Issue by GHpku** [KIAA-Galaxy/Group-Meeting#2]
test @darkbear9494 @TitaniumDioxide

**Comment by GHpku** [comment]
test comment

**Comment by GHpku** [comment]
test comment2

**Comment by TitaniumDioxide** [comment]
test succeed.

2016-03-17 18:15 GMT+08:00 Hua Gao <notifications@github.com>:

> test @darkbear9494 <https://github.com/darkbear9494> @TitaniumDioxide
> <https://github.com/TitaniumDioxide>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/KIAA-Galaxy/Group-Meeting/issues/2>
>



-- 
Zhuang Chu  庄楚

Undergraduate student at
Department of Astronomy
Peking University


E-mail:          zhuangchu@pku.edu.cn

           missinglyl@gmail.com

Cell Phone:  +86-18800109094
