### ISSUE TITLE
Nuclear Activity in Circumnuclear Ring Galaxies

### ISSUE THREAD

**Issue by GHpku** [KIAA-Galaxy/Group-Meeting#3]
[Nuclear Activity in Circumnuclear Ring Galaxies](http://arxiv.org/abs/1605.02847)

@darkbear9494 @yulin-zhao

**Comment by darkbear9494** [comment]
Thanks for the reminder. Maybe @yulin-zhao can talk about the paper in the group meeting this week?

**Comment by yulin-zhao** [comment]
I’m reading it now.

**Comment by GHpku** [comment]
I kind of regret mentioning this paper to you since the journal and the figures in the paper seem not quite professional. But I can't judge the paper by a quick glance. Hope you will find out whether it is a useful paper or not without wasting much time.

**Comment by darkbear9494** [comment]
Well, the figures indeed looks a bit strange, but as long as there sample is not so biased which it seems they have payed attention to, the results are meaningful. We can discuss tomorrow after Yulin present it~


best,
Shangguan

**Comment by yulin-zhao** [comment]
It is painful to read the paper, the way it present and it organise ….
